/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as CenaRouteImport } from './routes/cena'
import { Route as EstufaRadioRouteImport } from './routes/estufa-radio'
import { Route as SendYourMusicRouteImport } from './routes/send-your-music'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const CenaRoute = CenaRouteImport.update({
  id: '/cena',
  path: '/cena',
  getParentRoute: () => rootRouteImport,
} as any)
const EstufaRadioRoute = EstufaRadioRouteImport.update({
  id: '/estufa-radio',
  path: '/estufa-radio',
  getParentRoute: () => rootRouteImport,
} as any)
const SendYourMusicRoute = SendYourMusicRouteImport.update({
  id: '/send-your-music',
  path: '/send-your-music',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/cena': typeof CenaRoute
  '/estufa-radio': typeof EstufaRadioRoute
  '/send-your-music': typeof SendYourMusicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/cena': typeof CenaRoute
  '/estufa-radio': typeof EstufaRadioRoute
  '/send-your-music': typeof SendYourMusicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/cena': typeof CenaRoute
  '/estufa-radio': typeof EstufaRadioRoute
  '/send-your-music': typeof SendYourMusicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/artists' | '/cena' | '/estufa-radio' | '/send-your-music'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/about' | '/artists' | '/cena' | '/estufa-radio' | '/send-your-music'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/artists'
    | '/cena'
    | '/estufa-radio'
    | '/send-your-music'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArtistsRoute: typeof ArtistsRoute
  CenaRoute: typeof CenaRoute
  EstufaRadioRoute: typeof EstufaRadioRoute
  SendYourMusicRoute: typeof SendYourMusicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cena': {
      id: '/cena'
      path: '/cena'
      fullPath: '/cena'
      preLoaderRoute: typeof CenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estufa-radio': {
      id: '/estufa-radio'
      path: '/estufa-radio'
      fullPath: '/estufa-radio'
      preLoaderRoute: typeof EstufaRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-your-music': {
      id: '/send-your-music'
      path: '/send-your-music'
      fullPath: '/send-your-music'
      preLoaderRoute: typeof SendYourMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArtistsRoute: ArtistsRoute,
  CenaRoute: CenaRoute,
  EstufaRadioRoute: EstufaRadioRoute,
  SendYourMusicRoute: SendYourMusicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
